title: SMEFTsim
description: SMEFT LO simulations
author: Ilaria Brivio
email: ilaria.brivio@unibo.it
avatar: assets/images/smeftsim_logo_black.png

github_url: https://github.com/SMEFTsim
repository_url: https://github.com/SMEFTsim

show_downloads: false
theme: jekyll-theme-dinky
collections: [sections, tutorials]

